content:
  - name: posts
    label: Posts
    path: pages/posts
    type: collection
    fields:
      - name: date
        label: Date
        type: date
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: tag
        label: Tag
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: author
        label: Author
        type: string
        default: Raaid