content:
  - name: posts
    label: Posts
    path: pages/posts
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: string
      - name: description
        label: Description
        type: string
      - name: tag
        label: Tag
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: author
        label: Author
        type: string
        default: Raaid
  - name: about
    label: About
    path: pages/index.mdx
    type: file
    fields:
      - name: type
        label: Type
        type: string
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: body
        label: Body
        type: rich-text
  - name: blog
    label: Blog
    path: pages/posts/index.mdx
    type: file
    fields:
      - name: type
        label: Type
        type: string
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: body
        label: Body
        type: rich-text
  - name: projects
    label: Projects
    path: pages/posts/projects.mdx
    type: file
    fields:
      - name: type
        label: Type
        type: string
      - name: title
        label: Title
        type: string
      - name: date
        label: Date
        type: date
      - name: body
        label: Body
        type: rich-text